GET http://localhost:5000/api/v1/posts HTTP/1.1
authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmFtZXMiLCJpYXQiOjE2NDY5NjczNDQsImV4cCI6MTY0Njk2NzM1OX0.fgpa7GQxG60b64EjMFnW7uVtkHLwuxrD6HWOLOCFHC8
###
POST http://localhost:4000/api/v1/login HTTP/1.1
Content-Type: application/json

{
  "username": "James"
}
###
POST http://localhost:4000/api/v1/token HTTP/1.1
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmFtZXMiLCJpYXQiOjE2NDY5NjczMzZ9.aQop8q5k3DpsIF6E9O6a1lB4LhiqqG8OGiyS3cdYh58"
}
###

DELETE http://localhost:4000/api/v1/logout HTTP/1.1
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmFtZXMiLCJpYXQiOjE2NDY5NjczMzZ9.aQop8q5k3DpsIF6E9O6a1lB4LhiqqG8OGiyS3cdYh58"
}
###testing
POST http://localhost:5000/api/v1/users HTTP/1.1
Content-Type: application/json

{
  "name": "James",
  "email": "james@gmail.com",
  "password": "21678400"
}